#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo get-apt -y  update
sudo get-apt -y install nginx
echo 'Hello World!'| sudo tee /var/www/html/index.html
sudo service nginx start
